language: python
python:
  - "2.7"
  - "3.6"

env:
  - PLATFORMIO_PROJECT_DIR=examples/rtosal-freertos

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - platformio platform install file://.

script:
  - platformio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false

  slack:
    rooms:
      secure: IfMiWdHdWFuChxXqy52bjIAwu9s2QKuStJyhPNXzPshBxQE6b7yI6tJSmQ3cDF7XJr54AjrQNmGK8eCDkHNWeFAbNdBl7gAM0xHNpqXqqLOap3fXjeEgDua/bsqAjfKopXYY2jpUg2gMxyTUUPXB6Fcw7AlCyjCZLoz4uUH0e0XKA9VSqt2gnR7M3tzN/lRmGP/sn+jYv0alCJhzL0lyDbyKVQsX8X/onBmTqmXavJREG/KLhSMYSVw4UCbITEJWJBkShEasKDFpwe9V0wMuLi+NRqvQKnlYoiPLjIh2H4JExzWdbIzCa170Tuog47acHZUOIDACq5uesAa+pR1M3ZJDmnwATymhydAjU+qMJPfMCjmyveXYeRF3IcVpiwmUarnrGlU67PDiJQETaDizXl4YO5kVSWBvWml1Vt33oLVXCqnHO5mtO5OrlfprTt7jiqY6HBW0GLwhOxxKN3X6C18fM1Tgwpc2vwe6qYaT2UZLRVkZL+0miSxRvYsr60VNykSa1zNxym2e3MistIE833tg0C347U8PYZYNGqwFCabiioJsHRoxoJYLQMQj+uQyWMIhtXusZKWYA3C3Ap/5CyDxTijXi+zp/oi+Bw9QHfy+5ePJQgWzmzFDo0f/WppNITtL16gykStgiOk7azFZzB1WOae9/aCdt08Xg/kn7Hs=
    on_failure: always
    on_success: change
